package com.jfireframework.sql.dbstructure.impl;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.sql.DataSource;
import com.jfireframework.baseutil.collection.StringCache;
import com.jfireframework.baseutil.exception.JustThrowException;
import com.jfireframework.sql.mapfield.MapField;
import com.jfireframework.sql.metadata.TableMetaData;

public class H2DBStructure extends AbstractDBStructure
{
    public H2DBStructure(String schema)
	{
		super(schema);
	}

	@Override
    protected void _createTable(Connection connection, TableMetaData tableMetaData) throws SQLException
    {
        String tableName = tableMetaData.getTableName();
        MapField idInfo = tableMetaData.getIdInfo();
        StringCache cache = new StringCache();
        cache.append("CREATE TABLE ").append(tableName).append(" (");
        cache.append(idInfo.getColName()).append(' ');
        cache.append(getDesc(idInfo, tableMetaData));
        if (idInfo.getField().getType() == Integer.class || idInfo.getField().getType() == Long.class)
        {
            cache.append(" generated by default as identity(start with 1)  ");
        }
        cache.append(" primary key").appendComma();
        for (MapField each : tableMetaData.getFieldInfos())
        {
            if (each.getFieldName().equals(idInfo.getFieldName()))
            {
                continue;
            }
            try
            {
                cache.append(each.getColName()).append(' ').append(getDesc(each, tableMetaData)).appendComma();
            }
            catch (Exception e)
            {
                logger.error("{}类型不能识别，无法创建对应的建表语句.检查字段:{}", each.getField().getType().getName(), each.getField().toGenericString(), e);
                throw new JustThrowException(e);
            }
        }
        cache.deleteLast().append(")");
        logger.debug("进行表:{}的创建，创建语句是\n{}", tableName, cache.toString());
        connection.prepareStatement("DROP TABLE IF EXISTS " + tableName).execute();
        connection.prepareStatement(cache.toString()).execute();
    }
    
    
    protected void _updateTable(Connection connection, TableMetaData tableMetaData) throws SQLException
    {
        String tableName = tableMetaData.getTableName();
        String addColSql = "alter table " + tableName + " add ";
        String describeSql = "describe " + tableName + ' ';
        String modityColSql = "alter table " + tableName + " modify ";
        connection.prepareStatement("describe " + tableName).execute();
        MapField idInfo = tableMetaData.getIdInfo();
        ResultSet rs = connection.prepareStatement("describe " + tableName + " " + idInfo.getColName()).executeQuery();
        if (rs.next())
        {
            // 字段存在，需要执行更新操作
            if (idInfo.getField().getType() == Integer.class || idInfo.getField().getType() == Long.class)
            {
                logger.debug("执行sql语句:{}", "alter table " + tableName + " modify " + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData) + " generated by default as identity (start with 1)");
                connection.prepareStatement("alter table " + tableName + " modify " + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData) + " generated by default as identity (start with 1)").execute();
            }
            else
            {
                logger.debug("执行sql语句:{}", "alter table " + tableName + " modify " + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData));
                connection.prepareStatement("alter table " + tableName + " modify " + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData)).execute();
            }
        }
        else
        {
            // 字段不存在，需要执行新建动作
            if (idInfo.getField().getType() == Integer.class || idInfo.getField().getType() == Long.class)
            {
                logger.warn("执行sql语句:{}", addColSql + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData) + " generated by default as identity (start with 1)");
                connection.prepareStatement(addColSql + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData) + " generated by default as identity (start with 1)").execute();
            }
            else
            {
                logger.warn("执行sql语句:{}", addColSql + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData));
                connection.prepareStatement(addColSql + idInfo.getColName() + ' ' + getDesc(idInfo, tableMetaData)).execute();
            }
        }
        rs.close();
        for (MapField each : tableMetaData.getFieldInfos())
        {
            if (each.getColName().equals(idInfo.getColName()))
            {
                continue;
            }
            rs = connection.prepareStatement(describeSql + each.getColName()).executeQuery();
            if (rs.next())
            {
                logger.debug("执行sql语句:{}", modityColSql + each.getColName() + ' ' + getDesc(each, tableMetaData));
                connection.prepareStatement(modityColSql + each.getColName() + ' ' + getDesc(each, tableMetaData)).execute();
            }
            else
            {
                logger.debug("执行sql语句:{}", addColSql + each.getColName() + ' ' + getDesc(each, tableMetaData));
                connection.prepareStatement(addColSql + each.getColName() + ' ' + getDesc(each, tableMetaData)).execute();
            }
            rs.close();
        }
    }

	@Override
	protected boolean checkIfTableExists(Connection connection, TableMetaData metaData) throws SQLException
	{
		// TODO Auto-generated method stub
		return false;
	}
    
}
